### ISSUE TITLE
Sunny paaji's dialogue is incorrect

### ISSUE THREAD

**Issue by AkshayBz** [siddharthkp/dhai-kilo-ka-haath#1]
`Yeh dhai kilo ka haath jab kisi pe padta hai na
to woh uthta nahi uth jaata hai`
Should be:
`Jab yeh dhai kilo ka haath kisi pe padta hai na... to aadmi uthta nahi... utth jata hai`

**Comment by AkshayBz** [comment]
@siddharthkp: 2.5k ke liye kuch bhi 🤔

**Comment by siddharthkp** [comment]
Pull request is welcome ;)

**Comment by siddharthkp** [comment]
Fixed in https://github.com/siddharthkp/dhai-kilo-ka-haath/commit/cc0b7d537659f3d96e6aae5a9b0876ad251b8b6a 💪

**Comment by AkshayBz** [comment]
👏 Few bytes didn't impact the KBs 😛

**Comment by siddharthkp** [comment]
It's still exactly 2.5 * 1024

Removed some whitespace to maintain it ;)
